[package]
name = "blazebooru_models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
serde = "1.0.190"
serde_derive = "1.0.190"
uuid = "1.5.0"
